---
title: "EPID674 Epidemiologic Data Analysis using R"
subtitle: "Hypothesis Testing in R"
author: "Kelly Bakulski, Lauren Middleton"
date: "Last compiled on `r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

### Install new packages
```{r install_packages, eval=FALSE, include=FALSE}
# Install packages. Do this only once. 
options(repos="https://cran.rstudio.com" )
install.packages("epiDisplay")
install.packages("corrplot")
install.packages("here")
install.packages("tidyverse")
install.packages("infer")

# To avoid installing every time: in curly brackets set eval=FALSE
```

### Load packages
```{r load_packages, message=FALSE}
##### Load these packages for the current session
library(here)
library(tidyverse)
library(ggcorrplot)
library(gtsummary)
library(epiDisplay)
```


# Load data
```{r load_data}
# Check the file path
here("nhanes_dataset.rda")
# Load the saved R data
load(here("nhanes_dataset.rda"))
```


# Basic statistical tests in R

### Remember to check your distributions/assumptions
```{r histograms_continuous}

# Make a simple base R histogram
hist(nhanes_dataset$LBXIRN)

# For loop to make histograms of all numeric variables in dataset
for (i in 1:ncol(nhanes_dataset)) {
  if(is.numeric(nhanes_dataset[,i])==T) {
     hist(nhanes_dataset[, i], main = colnames(nhanes_dataset)[i])
    }
}

#ggplot version - doesn't work
for (i in 1:ncol(nhanes_dataset)) {
  if(is.numeric(nhanes_dataset[,i])==T) {
     print(ggplot(nhanes_dataset, aes(i)) +
             geom_histogram() +
             labs(title = colnames(nhanes_dataset)[i]))
    }
}
```


### Correlation tests
```{r correlation_tests}
# Correlation test between two continuous variables (default is Pearson)
cor.test(nhanes_dataset$RIDAGEYR, nhanes_dataset$INDFMPIR)

cor.test(nhanes_dataset$RIDAGEYR, nhanes_dataset$INDFMPIR, method = "spearman")
```


### Correlation matrix
```{r correlation_matrix}
# Select the columns with chemicals
nhanes_chems <- nhanes_dataset %>%
  select(LBXIRN,
         LBXCOT,
         LBXBCD,
         LBXBPB,
         LBXWBCSI,
         LBXRBCSI)

# Calculate the correlations
chem_correlations <- cor(nhanes_chems,
                         use = "pairwise.complete.obs",
                         method = "spearman")

# View the correlation matrix
View(chem_correlations)

# Plot the correlations with ggcorrplot
ggcorrplot(chem_correlations,
           type = "lower",
           outline.col = "white",
           lab = TRUE)
```

### T-test and Wilcoxon test
```{r ttest_wilcoxon} 
# The relationship between sex and iron concentration:
# What do you expect?

# Calculate mean of iron concentration by sex
nhanes_dataset %>%
  group_by(sex) %>%
  summarise(mean_iron = mean(LBXIRN, na.rm = TRUE)) %>%
  ungroup()

# T-test of iron and sex
t.test(nhanes_dataset$LBXIRN ~ nhanes_dataset$sex) #What do you get? 
# Do they match?



# The relationship between sex and blood Pb:
nhanes_dataset %>%
  group_by(sex) %>%
  summarise(mean_lead = mean(LBXBPB, na.rm = TRUE),
            mean_log_lead = mean(log10(LBXBPB), na.rm = TRUE)) %>%
  ungroup()

# T-test
t.test(log10(nhanes_dataset$LBXBPB) ~ nhanes_dataset$sex)

# Wilcoxon test
wilcox.test(nhanes_dataset$LBXBPB ~ nhanes_dataset$sex)
```

### ANOVA
```{r anova}
# The relationship between age and blood Pb:
nhanes_dataset %>%
  group_by(age_groups) %>%
  summarise(mean_lead = mean(LBXBPB, na.rm = TRUE),
            mean_log_lead = mean(log10(LBXBPB), na.rm = TRUE)) %>%
  ungroup()

# ANOVA test
aov(log10(nhanes_dataset$LBXIRN) ~ nhanes_dataset$age_groups)
anova(aov(log10(nhanes_dataset$LBXIRN) ~ nhanes_dataset$age_groups))
# How do we interpret the p-value from an ANOVA test?

# Pairwise t-test
pairwise.t.test(log10(nhanes_dataset$LBXIRN), nhanes_dataset$age_groups)

# Pairwise t-test with bonferroni adjustment
pairwise.t.test(log10(nhanes_dataset$LBXIRN), nhanes_dataset$age_groups,
                p.adj = "bonferroni")
```

# Chi-square test
```{r chisq_fisher}
# The relationship between sex and education:
nhanes_dataset %>%
  select(sex,
         education) %>%
  tbl_summary(by = sex, #stratify by sex
              label = list(sex  ~ "Sex"),
              statistic = list(all_categorical() ~ "{n} ({p}%)"), #row percentages
              digits = list(all_categorical() ~ c(0, 1)),
              missing_text = "Missing (n)"
              ) %>%
  add_p() %>%
  modify_header(label ~ "**Variable**") %>%
  bold_labels()


# Chi-square test
chisq_test(nhanes_dataset, sex ~ education)
```

#  Fisher's tests
```{r}

# The relationship between sex and iron status:
nhanes_dataset %>%
  select(sex,
         iron_status) %>%
  tbl_summary(by = sex, #stratify by sex
              label = list(sex ~ "Sex"),
              statistic = list(all_categorical() ~ "{n} ({p}%)"), #row percentages
              digits = list(all_categorical() ~ c(0, 1)),
              missing_text = "Missing (n)"
              ) %>%
  add_p() %>%
  modify_header(label ~ "**Variable**") %>%
  bold_labels()

# Fisher exact test
fisher.test(nhanes_dataset$sex, nhanes_dataset$iron_status)
```



# Odds Ratios from 2x2 table
```{r odds_ratio}

# Simplify iron into two categories
nhanes_dataset_iron <- nhanes_dataset %>%
  filter(!iron_status == "Excessive") %>%
  droplevels()
table(nhanes_dataset_iron$iron_status)

# Iron status levels: normal and deficient and sex
nhanes_dataset_iron %>%
  select(sex,
         iron_status) %>%
  tbl_summary(by = sex,
              label = list(sex  ~ "Sex"),
              statistic = list(all_categorical() ~ "{n} ({p}%)"), #row percentages
              digits = list(all_categorical() ~ c(0, 1)),
              missing_text = "Missing (n)"
              ) %>%
  modify_header(label ~ "**Variable**") %>%
  bold_labels()

# calculate odds ratio
cc(outcome = nhanes_dataset_iron$iron_status,
   exposure = nhanes_dataset_iron$sex)
```




# Create fake data for graphing odds ratio results
```{r setup_data_for_forestplot}
## Assuming that you obtained ORs for all and by sex and race.
## Let's create a data frame for these ORs and 95% CIs.

x_num <- c(1, 3, 4, 6, 7)
x1 <- c("Overall", "Male", "Female", "White", "Black")
or <- c(1.5, 1.1, 2.0, 1.4, 1.6)
or_lower_lim <- c(1.2, 0.9, 1.65, 0.95, 1.3)
or_upper_lim <- c(1.85, 1.35, 2.4, 2.05, 2.0)
results <- data.frame(x_num, x1, or, or_lower_lim, or_upper_lim)
results$x1 <- factor(results$x1,
                     levels = results$x1)
```


```{r forest_plot_ggplot2}
# Forest plot, ggplot2 package
ggplot(results,
       aes(x = or,
           y = x1,
           xmin = or_lower_lim,
           xmax = or_upper_lim)) +
  geom_pointrange() +
  xlab("Odds Ratio") +
  ylab("Group") +
  geom_vline(xintercept = 1,
             linetype = 2)
```

